---
  # See appveyor.yml for windows build.
  sudo: required
  language: go
  dist: trusty
  osx_image: xcode10.1
  os:
    - linux
    - osx
    - linux-ppc64le
  notifications:
    email: false
  go:
    - 1.12.x
  addons:
    apt:
      packages:
        - libsecret-1-dev
        - pass
  before_script:
    - make deps
    - "export DISPLAY=:99.0"
    - if [[ "$TRAVIS_OS_NAME" == "linux" && "$HOSTTYPE" != "powerpc64le" ]]; then sh ci/before_script_linux.sh; fi
    - make validate
  jobs:
    include:
      - stage: test
        script: make test
      - stage: deploy
        script: make pass
        os: osx
        deploy:
          provider: releases
          api_key: $GITHUB_OAUTH_TOKEN
          file: "bin/docker-credential-pass"
          skip_cleanup: true
          on:
            tags: true
